//
//  ScenePresenter.swift
//  FeaturedApp
//
//  Created by Reza Harris on 25/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScenePresentationLogic
{
  func presentFeature(response: Scene.Feature.Response)
}

class ScenePresenter: ScenePresentationLogic
{
  weak var viewController: SceneDisplayLogic?
  
  // MARK: Do something
  
  func presentFeature(response: Scene.Feature.Response)
  {
    let viewModel = Scene.Feature.ViewModel()
    viewController?.displayFeature(viewModel: viewModel)
  }
}
