//
//  SceneInteractor.swift
//  FeaturedApp
//
//  Created by Reza Harris on 25/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SceneBusinessLogic
{
  func feature(request: Scene.Feature.Request)
}

protocol SceneDataStore
{
  //var name: String { get set }
}

class SceneInteractor: SceneBusinessLogic, SceneDataStore
{
  var presenter: ScenePresentationLogic?
  var worker: SceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func feature(request: Scene.Feature.Request)
  {
    worker = SceneWorker()
    worker?.doSomeWork()
    
    let response = Scene.Feature.Response()
    presenter?.presentFeature(response: response)
  }
}
