//
//  ListOrdersInteractor.swift
//  FeaturedApp
//
//  Created by Reza Harris on 23/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic
{
  func fetchOrders(request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersDataStore
{
  var orders: [Order]? { get }
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
  var presenter: ListOrdersPresentationLogic?
  var ordersWorker = OrdersWorker(orderStore: OrdersMemStore())
  var orders: [Order]?
  
  // MARK: Do something
  func fetchOrders(request: ListOrders.FetchOrders.Request)
  {
    ordersWorker.fetchOrders { (orders) -> Void in
      self.orders = orders
      let response = ListOrders.FetchOrders.Response(orders: orders)
      
      self.presenter?.presentFetchedOrders(response: response)
    }
  }
}
