//
//  ShowOrderInteractor.swift
//  FeaturedApp
//
//  Created by Reza Harris on 23/12/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowOrderBusinessLogic
{
  func getOrder(request: ShowOrder.GetOrder.Request)
}

protocol ShowOrderDataStore
{
  var order: Order! { get set }
}

class ShowOrderInteractor: ShowOrderBusinessLogic, ShowOrderDataStore
{
  var presenter: ShowOrderPresentationLogic?
  var order: Order!
  
  func getOrder(request: ShowOrder.GetOrder.Request) {
    
    let response = ShowOrder.GetOrder.Response(order: order)
    presenter?.presenterOrder(response: response)
  }
}
